# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='creation_time',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
