# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170216_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
