# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170216_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='creator',
            new_name='created_by',
        ),
    ]
