# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProxy')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='anonymous',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
