# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170219_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProxy')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(related_name='_room_members_+', through='api.Membership', to='api.UserProxy'),
        ),
        migrations.AddField(
            model_name='message',
            name='likes',
            field=models.ManyToManyField(related_name='_message_likes_+', through='api.Like', to='api.UserProxy'),
        ),
    ]
