# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_likeroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserProxy')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('user', 'device')]),
        ),
    ]
